name: Create Release

on:
  push:
    tags:
      - "supuesto-ideal-v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Supuesto Ideal - Sistema de Prevención de Caídas
          generate_release_notes: true
          files: |
            runs/yolov8s_zoom/weights/best.pt
            yolov8s.pt
            setup.sh
